version: '3.8'
services:
  php:
    container_name: "Techbazaar"
    image: php:8.1.16-apache
    volumes:
      - ./codigo/:/var/www/html/
    ports:
      - 89:80
  db:
    image: mariadb:10.5
    container_name: 'bd_tech'
    restart: always
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=123
  adminer:
    image: adminer:4.8.1
    container_name: "adminer_tech"
    restart: always
    ports:
      - 812:8080